Repository kelsiebesingeryeh/Crate, pull requests merged in 2021-03, with the labels that each got.

#52 Feature/survey route
  code/web/src/modules/crate/Item.js
  code/web/src/setup/routes/crate.js
Labels: Frontend, Survey

#53 New migrations
  code/api/src/migrations/5-add-columns-to-products.js
  code/api/src/migrations/6-add-column-to-subscriptions.js
  code/api/src/migrations/7-add-columns-to-crates.js
  code/api/src/migrations/8-change-style-tag-on-products.js
  code/api/src/modules/crate/model.js
  code/api/src/modules/crate/types.js
  code/api/src/modules/product/model.js
  code/api/src/modules/product/types.js
  code/api/src/modules/subscription/model.js
  code/api/src/modules/subscription/types.js
  code/api/src/seeders/3-crates.js
Labels: Backend

#57 Feature/setup jest
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/survey/Survey.test.js
Labels: FE Test
